baseURL = "https://die-partei.sh/"
languageCode = "de-de"
title = "Die PARTEI"
theme = "die-partei"
uglyurls = false
categories = false
tags = false
canonifyURLs = true

[permalinks]
post = "/:section/:slug"
node = "/:filename"

[params]
author = "Die PARTEI - Landesverband Schleswig-Holstein"
avatar = "square.jpg"
